In [1]:
# how to load cvs files in jupyter

In [2]:
import pandas as pd

In [23]:
mydataset = pd.read_csv("C:\\Users\\alan\\AI Project\\pandas_tutorial.csv",delimiter=';',
                        names = ['my_datetime', 'event', 'country', 'user_id', 'source', 'topic'])
# read the file from local, make sure use \\ instead of \

In [24]:
myvar = pd.DataFrame(mydataset)

In [25]:
myvar

              my_datetime event    country     user_id   source          topic
0     2018-01-01 00:01:01  read  country_7  2458151261      SEO  North America
1     2018-01-01 00:03:20  read  country_7  2458151262      SEO  South America
2     2018-01-01 00:04:01  read  country_7  2458151263  AdWords         Africa
3     2018-01-01 00:04:02  read  country_7  2458151264  AdWords         Europe
4     2018-01-01 00:05:03  read  country_8  2458151265   Reddit  North America
...                   ...   ...        ...         ...      ...            ...
1790  2018-01-01 23:57:14  read  country_2  2458153051  AdWords  North America
1791  2018-01-01 23:58:33  read  country_8  2458153052      SEO           Asia
1792  2018-01-01 23:59:36  read  country_6  2458153053   Reddit           Asia
1793  2018-01-01 23:59:36  read  country_7  2458153054  AdWords         Europe
1794  2018-01-01 23:59:38  read  country_5  2458153055   Reddit           Asia

[1795 rows x 6 columns]